# Generated by Django 4.1.5 on 2023-02-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_userchoices_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoices',
            old_name='question_id',
            new_name='question',
        ),
    ]
